name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./server
        run: npm ci --include=dev

      - name: Run tests
        working-directory: ./server
        run: npm test
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          NODE_ENV: test
          PORT: 3000
          REDIS_URL: ${{ secrets.REDIS_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          FROM_EMAIL: onboarding@resend.dev
          CLIENT_URL: http://localhost:5173